# name: Build and Validate
# on:
#   pull_request:

# jobs:
#   build:
#     strategy:
#       matrix:
#         dockerfile: [image-upload/Dockerfile]
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to Dockerhub registry
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Build image ${{matrix.dockerfile}}
#         uses: docker/build-push-action@v2
#         with:
#           push: false
#           context: .
#           file: ${{matrix.dockerfile}}
#           platforms: linux/amd64
#           tags: itspuneet59/gh-images-new:latest

#       - name: Build image ${{matrix.dockerfile}}
#         uses: docker/build-push-action@v2
#         with:
#           push: false
#           context: .
#           file: ${{matrix.dockerfile}}
#           platforms: linux/arm64
#           tags: itspuneet59/gh-images-new:latest
