name: Publish artifacts
on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        dockerfile: [image-upload/Dockerfile]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine version
        id: version
        run: echo ::set-output name=version::$(git describe --abbrev=0 --tags)

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build arch specific image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          tags: gh-img-x86_64:1.2.0
          outputs: type=docker,dest=/tmp/gh-img-x86_64.tar
          # tags: ghcr.io/puneet-work/images/gh-img-x86_64:1.2.0

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: gh-img-x86_64
          path: /tmp/gh-img-x86_64.tar

      - name: Build arch specific image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/arm64
          tags: gh-img-aarch64:1.2.0
          outputs: type=docker,dest=/tmp/gh-img-aarch64.tar
          # tags: ghcr.io/puneet-work/images/gh-img-aarch64:1.2.0

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: gh-img-aarch64
          path: /tmp/gh-img-aarch64.tar

  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'download for x86'
        uses: actions/download-artifact@v2
        with:
          name: gh-img-x86_64
          path: /tmp
      - name: 'download for aarch64'
        uses: actions/download-artifact@v2
        with:
          name: gh-img-aarch64
          path: /tmp
      - name: Load images
        run: |
          docker load --input /tmp/gh-img-x86_64.tar
          docker load --input /tmp/gh-img-aarch64.tar
          docker image ls -a
          docker manifest inspect gh-img-x86_64:1.2.0
          docker manifest inspect gh-img-aarch64:1.2.0
      # - name: 'stitch multiplatform'
      #   run: |
      #     docker manifest create \
      #       ghcr.io/puneet-work/images/gh-img:1.2.0 \
      #       --amend ghcr.io/puneet-work/images/gh-img-x86_64:1.2.0 \
      #       --amend ghcr.io/puneet-work/images/gh-img-aarch64:1.2.0

      #     docker manifest inspect ghcr.io/puneet-work/images/gh-img:1.2.0
      #     docker manifest push ghcr.io/puneet-work/images/gh-img:1.2.0

      #     # docker manifest annotate --arch amd64 gh-img:1.2.0 gh-img-x86_64:1.2.0
      #     # docker manifest annotate --arch arm64 gh-img:1.2.0 gh-img-aarch64:1.2.0

      #     # docker manifest inspect --verbose gh-img:1.2.0

      #       # ghcr.io/puneet-work/images/gh-img:manifest-latest \
      #       # --amend your-username/multiarch-example:manifest-amd64 \
      #       # --amend your-username/multiarch-example:manifest-arm32v7 \
      #       # --amend your-username/multiarch-example:manifest-arm64v8

      # - name: 'stitch multiplatform'
      #   run: |
      #     docker manifest create \
      #       ghcr.io/puneet-work/images/gh-img:1.2.0 \
      #       --amend localhost:5000/name/gh-img-x86_64:1.2.0 \
      #       --amend localhost:5000/name/gh-img-aarch64:1.2.0

      #     docker manifest inspect ghcr.io/puneet-work/images/gh-img:1.2.0
      #     docker manifest push ghcr.io/puneet-work/images/gh-img:1.2.0

      #     # docker manifest annotate --arch amd64 gh-img:1.2.0 gh-img-x86_64:1.2.0
      #     # docker manifest annotate --arch arm64 gh-img:1.2.0 gh-img-aarch64:1.2.0

      #     # docker manifest inspect --verbose gh-img:1.2.0

      #       # ghcr.io/puneet-work/images/gh-img:manifest-latest \
      #       # --amend your-username/multiarch-example:manifest-amd64 \
      #       # --amend your-username/multiarch-example:manifest-arm32v7 \
      #       # --amend your-username/multiarch-example:manifest-arm64v8
