name: Publish artifacts
on:
  pull_request:

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine version
        id: version
        run: echo ::set-output name=version::$(git describe --abbrev=0 --tags)

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image ${{matrix.dockerfile}}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile-${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          tags: puneet-work/images/gh-img:${{steps.version.outputs.version}},puneet-work/images/gh-img:latest
